language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - add-on
    - extra

  licenses:
    - 'android-sdk-license-.+'

  notifications:
    email: false

before_install:
    - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew build connectedCheck --info
